apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: global-inflight
  namespace: kube-system
spec:
  inFlightReq:
    amount: 1000
    sourceCriterion:
      requestHost: true
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      spec:
        externalTrafficPolicy: Local
    ports:
      web:
        middlewares:
          - kube-system-global-inflight@kubernetescrd
      websecure:
        middlewares:
          - kube-system-global-inflight@kubernetescrd
