apiVersion: v1
kind: Secret
metadata:
    name: registry-credentials
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:lZ6VMHGuY59dyoOcfnsMpzm7BhNYZNR52633yupTUbBQqLyBpv5Hgjl1sxdGoH1MUrDxvvTw/c1M24ZqB8Y/w6Q7cF0vy4ElsqXEyOitxa7TJodDQk56uN+jJ4kcKPwBlKNFn7bqh2ALEThMZ0ssei0wW0jUqhrEJM+KztmXCyxoY7fAIttlz+qXSNpPhJy0a3Su/AKT9ZZtbjFYz6UUJ9+NTBU=,iv:Bbgtc25Y3yhyLBeYLb05EGX5Wf+sCjtX2FjTF2Ryj20=,tag:3wIwHxlBnEJMGSZeR36gJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLV1FnQnpIQXY0ZEFWTVRF
            VHEzS2Fsc2VjanpsVjl6T0RnTVFvMmR6em5ZCjAzWW4rZnlSMEFodjROTVNnQjh6
            eFNjWG9OUDlyUEJmSWIxMmVRZkc4aWcKLS0tIE82L3FheGkwNjJUVEpsczBlYnZv
            YnQrMHd4TlhPMGhuM1dqakwrSG1RNjQKPHsqyagxDmnCDmNwiSyQG5w1l8OAi/3A
            lLGjhaed1L22bR1+o4f5TYH5xtFXkPcbsCoupnERQM8suSACJ6Bbhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mrzxnhevexdaywfjepmxhq5vu84zshcf34z9he056zqwcxvv8vus8970cc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNzlHVldUbUF4WGFwb2RE
            MkxwMlRPelZLTlFXTWp2UjRncnlGUnh5NVJnCkRnY2F2MVp2M0I5dTNXN0IwWW9L
            TGVqMFZQczZxeDFFSGJLRFZVZDdXd00KLS0tIGNaa21aZmx6NHNLdnp1dW1KZ3Nu
            bW85c1N6NjExejN1TDU0MksySlZVbGcKDXwnr/+bok29LE87zXbYy0+oYKwXuTzh
            1z9nXOwTHGhPSRYRpnN0107iw/SX7IULcWDVwNk1d2L40jI9mDQFYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fqwlewvwa72jne30juy5u8nxkyy0x4dd06f0x0r984lmvexe954s2k5mx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T01:43:57Z"
    mac: ENC[AES256_GCM,data:zETq1mfwOgMpgY+uHjgOIQPMvZQiGQWFJTwumZiP126PUvy5PrmAuNRz61C+2IwemfGnvQtxvjsDjZXkk9R7COD7gXn2ZKns3FZkkRMUM7NvPdKTMtvs1Jel421AaHrUCkwuJoXXNVDyBT+1GmbdLjoBECxAdNbAYnVxoSlpGBM=,iv:3ngp2+yP4GO+kqBzVXNZUMBI3cm8zY3nzqId9qFHvgg=,tag:WhAw8ivmPnv2owE2MTjXvw==,type:str]
    version: 3.13.2
