apiVersion: v1
data:
    password: ENC[AES256_GCM,data:eggwfbSFBvwxvZnllzZKiw==,iv:g32yPy4DFKqlzpZIUzW5vh4XPKvK0xV02Ipj/b+yS/Y=,tag:OFgbRSzN8jyQSV3F3JyCrw==,type:str]
    username: ENC[AES256_GCM,data:qPPl1/al36frqrWw,iv:umTwAkhsoJdDomg8TdQImLfNKBee0d2jHYUeNSsWlm8=,tag:sFQQc+ZAJgrMdeD5N73afw==,type:str]
kind: Secret
metadata:
    name: registry-credentials
    namespace: flux-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dVlHam92WU5RVjh5a3I1
            NStSd1k3V2pCQzZ6OWlRT0RtcHlsaWFBUEhFCmtkVFR6bjFadEs3RTJSaXJQT2Zy
            S05yMVgxeEZpdVErTy9EVHM2VncxclEKLS0tIHZmSWdaS05yL205eldUSisyS3Jv
            ak0vdFo1M2x3UDFSRXNnOXRzMnhUY00KkgHhMiGhQOcS0nKD4rZKLN2fgzdnNWfr
            muoD48gLXbAiN4f2eOIfd0BwK8Yfzt29XF2j6o+ic455e6VQPCBf9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mrzxnhevexdaywfjepmxhq5vu84zshcf34z9he056zqwcxvv8vus8970cc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY1RjTTdGUVp1NEt0OCtk
            QXZRQjlMaDd1bEJQRElMQ1Z3ZXBCTTA1RFRrCkpMWXdDN2Y1dXZQZ3RkMy94T2FY
            WWpMcjZ2d0pmS2JLVVErZ3kvdndMeUEKLS0tIG9vNlhVVnpjQVF0QWdPU1RaTE5H
            VjR1alVMZW9yM0E5YVNSNXdzNDlNZjQKRpKS5TsAn4Uw1r0WOkiR2dz+Zv2LD8PV
            eFnqbz8cM+UD83qH/OpmRIkgoKPOrnxeklxwafwdaJmgP150l2lIMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fqwlewvwa72jne30juy5u8nxkyy0x4dd06f0x0r984lmvexe954s2k5mx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T16:28:40Z"
    mac: ENC[AES256_GCM,data:WqyN5hJenN32oqgzKg1qYH5ZDORmYpPXCiINxtsUt0WwEucJtEWoukl4HZq01ekS/3zA6jSZk3CdPYboSC32qMdq7jmTP7VRcOtKlNtxFfR9AXnolF1M5LHKWZObpm696RpuHMjjZ/N1gNot64MzBjem94RntYFo6e0Vul8Fdq8=,iv:sgKky6XTs2ZWqCs7RiNHQu/hLnyzyTCnYfHvHLVKd2I=,tag:YKnN28c12Bwg5e91FJoTqw==,type:str]
    version: 3.13.3
