apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-config
  namespace: registry
data:
  config.json: |
    {
      "storage": {
        "rootDirectory": "/var/lib/registry",
        "gc": true,
        "gcDelay": "1h",
        "gcInterval": "24h",
        "dedupe": true
      },
      "http": {
        "address": "0.0.0.0",
        "port": "5000",
        "auth": {
          "htpasswd": {
            "path": "/auth/htpasswd"
          }
        }
      },
      "log": {
        "level": "info"
      }
    }
