apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry
  namespace: registry
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: registry-tailscale-only@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - registry.sh-lucas.dev
    secretName: registry-tls
  rules:
  - host: registry.sh-lucas.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: registry
            port:
              number: 5000
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: tailscale-only
  namespace: registry
spec:
  ipAllowList:
    sourceRange:
      - 100.64.0.0/10
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-traefik-only
  namespace: registry
spec:
  podSelector:
    matchLabels:
      app: registry
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 5000
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: flux-system
          podSelector:
            matchLabels:
              app: image-reflector-controller
      ports:
        - protocol: TCP
          port: 5000
