apiVersion: v1
kind: Secret
metadata:
    name: registry-auth
    namespace: registry
type: Opaque
data:
    htpasswd: ENC[AES256_GCM,data:mjICWchBP2p9zdTVSQuMDOadtQ+dRP381dSei1pMENf2XWiJ+jywx5IuaYrpv8tYemxnVxKKgy/oHkWDSSPufol8kb/Gncym+Oq+xf6FXG+84Fms98iiNNNbHWniT5qQBuET1IXLSENKEyC+4O8jniwBkC7KxhMvlblrwcU11e59Qf/vl/KcGPoAlUOx/aaiLBjaLlTef9HuRJzfqs1u0JnqaI88KPLZL3E8MCk5yAjO/dXVMmjMmKlwT9S2fDw0,iv:YpgMlITvlpwGOxvu2lXAiWjVMdr7za+YPCiIXHDl8M4=,tag:b4ysjrk8qzWzxn3UBF41AQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YThRbWx6U1pBaE5oWUU2
            bEsxSzBZZkxEbmtobURBK0JJd3ppQ0JEdDJNCkhxMGtVRVhrMFFZeEhBbE1tUWhK
            RGFrYWFMa0c5cXZ6OURYWWFKUWtrT1EKLS0tICttZkpBOVRudXBBdkZ5R2VNRWo5
            TVlYcjQyQ0wrUUpoYXEvbTRhSENEZ00KgqLD8jWt/6GQbQrygCsCQyzMyxE3eCsF
            qHxyFI/v9dcKz2qyhXa58I0ITsRMoukRIrAMwqwEYycsgCidl5WPfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mrzxnhevexdaywfjepmxhq5vu84zshcf34z9he056zqwcxvv8vus8970cc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlY0lDSS93MVRRMHN2dnp1
            alFPSmRuQVhQSE9XR0V0aEtpQlNHZ1FodkFRCkI5WjN2dTVCYnFNN1pCcU84aDN0
            QjNnV0FUOXlDWXJtSk9iaTdRT3VjY0kKLS0tIFlCNE9mSldqd3o1VWo1bjh6UFMw
            WEpvVDNKUDJITVo2a1NTQzY1eE5zaEUK6svcoKaTLGSh6dUJoi4rWaq1vv4wHClr
            tFi3M5zZfkhyeHj9/R5C9YVTgU5qOgdcF4aE9bsDa02R0HGWXWX18A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fqwlewvwa72jne30juy5u8nxkyy0x4dd06f0x0r984lmvexe954s2k5mx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T01:43:53Z"
    mac: ENC[AES256_GCM,data:z3XiTjhFWSMm0olOyAiDAwWb5/lR7iMXIBbh0p7YYjmA1XcpeW9/18GsgOMJV+XbYzO6OxHTBtR8SfqlpWxJVNgQZ+/pcmPHrYyaWY+Cv8/3pO3QiAaxqj1++xq56547TqMaTH1D59j8JVkEW4ImtNrGdHYd1bgw8ayxG6AtNY0=,iv:gAyOJy+ON3cFaBIQR081f4nCtuZDyvdwftIPCzzJwdo=,tag:+CxCtHKSh6eaQXJqm88NKg==,type:str]
    version: 3.13.2
