apiVersion: v1
kind: Secret
metadata:
    name: registry-auth
    namespace: registry
type: Opaque
stringData:
    htpasswd: ENC[AES256_GCM,data:2l81NfwFJKjTf7Vu4BpuHxtTTWbwkDzxIKJH/KHRyCKQf42H5xY9Dfv4O4b0zb0zgrNA0K8NB4dFYLx+ZTVNd8/DfjEDkPmlZ7KUeGCqjTpkPD66MaOnIGBYDW0wzoD6zvgEfvdFFtKjAdblMYBgjB6NcDOFWLiFVY1MVVP2UBtcGOIXsxoFgc2t1AblQg==,iv:WH7kXIqCcXq62S2syrwSQg+OygFnRczRx4A6XQVYFvQ=,tag:16u+bvMTEs7LA75Ail16Qg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzM3VtRlF5RUM3bTYvNXZD
            K3RxSTByS0xaZlo0Rmpvc1Njbk5LTFNqdGpVCjB0UGp1TEZkTHFxZVlLKytsTERN
            M01TTGZQNFZjUjVJdTRENXEveXpGU1EKLS0tIHFBS241bWZtaWxWM1Jac3JsL3VW
            RzNJeDFDL2pEN0ZmTnBhSHBvZ1FrM2sK+/YxqsU2BEP7UNNNxvL+N/yu8DkoNCil
            RzRU0FZvDtKqeYeaWvV6tsptX0e+h0TGVvzJFwBcIxdHn+LMSjDJtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mrzxnhevexdaywfjepmxhq5vu84zshcf34z9he056zqwcxvv8vus8970cc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6d0xHNWkzMXB0QlhDOEN0
            UXJKV0hZbGhZWmM5Y0h6azNHQXRjRy96MDNFCjBiY3lpZ1hZOW00ZTNsYXVzTnN2
            OXlBYm9Kdld3SnZjTSs0elo5MjlvSGMKLS0tIEZJN2N2UVhDM2Z1QkFJMlc0WEw3
            Vmt1OXU4V3ZXUDRUTjVBSVJacEZwVEUKuptBDccvcKObxJPhypgU5spsy4IwS0xR
            5EoLBRJ3r1/bCdBugoA5t9zwcDQtortVU03XpDOxYyDyXGZoTs7adg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fqwlewvwa72jne30juy5u8nxkyy0x4dd06f0x0r984lmvexe954s2k5mx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T16:28:40Z"
    mac: ENC[AES256_GCM,data:zt4pv8BXv9owQwX7RaxoL2Hrff/7H9J6Eot+dKVn6v1H66xhasvBKymIpIl+yULQFIc+jsRO56xWN8MLqp9YEAA6WZqD0KF2ca4NTdko1biVVrMMoBl2aRmAFY+NfpFBHRZWDmUbqlkC1KQLV7iZ8dTKgUUYNt5jUc3XalmH6LY=,iv:cjVHjFc4J2ghwWeozDzjoQ5E2wOeXIja+d+nGGtxM34=,tag:AjhLBVfPuqvQ5aqPZZNoEQ==,type:str]
    version: 3.13.3
