apiVersion: v1
kind: Secret
metadata:
    name: openobserve-credentials
    namespace: observability
type: Opaque
data:
    password: ENC[AES256_GCM,data:WcxFVQ1bjpH4+ktWHLPNQA==,iv:9xiYdWkiuU4AK+peSOFtpicsi4Y03Rvmbe8G4JMDwAs=,tag:m7r/JkiXGGZvfgG8DfD4ig==,type:str]
    username: ENC[AES256_GCM,data:1Ge1vfFspK6bDZM44987LruK783tz+4tf/vbHKGHNCOxhjtIrSLXVg==,iv:Wl7pvLyiF0Js4ZzP6NjeObjqecb8JUFTV1UwoVknXYs=,tag:04g1Tv7bw09eigowqXBbxw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTy9xQWlJeEpxN0liWHg1
            ZWNKQ3pSY05QQXF3aUhaTFAzcGI0ZFJWcDJzCkwrNHpPODljRlhzTUtwV2pOS0du
            YjZUL3ZyemRmKzI3QjdFYXlxd29wQzAKLS0tIE1HZlNCcWdXb1RXaXlzSDM5MGk1
            emtGOHpnS1RsaHp6aWNTZElYeDQxYmcKnVxeycBcKkUeLyrTvKx3RI71ibPr10qS
            A+NRKwUQKwg8vKfqhiwJ2m080MNNKwfM3qQlBFNAKFfjZcFhbE2z5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mrzxnhevexdaywfjepmxhq5vu84zshcf34z9he056zqwcxvv8vus8970cc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZkJOekZHZmN2WGRndkE3
            OXV5dWVzZ2NoZ0RDU0E4b1RzZUhzd0MxN0VJCjZiUm53RGhYeC9ubmxKdEltMEly
            eUdmNnFGR0Q5RzJJSGVsRTJ0NUVHTjAKLS0tIDNoTzFhRitlaTJ5dngvL1N3V2lz
            bzk3Vkw5eXk2TWkzYWdYNXJLMUVRSGcKMqA9M3HQPVfzxZ5wKQKNniDRront9oIC
            BFEor6GwHjczKwrKu5rT8NmZpAMIK3vTrIwoLpXizNyiWq+JnWXuWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fqwlewvwa72jne30juy5u8nxkyy0x4dd06f0x0r984lmvexe954s2k5mx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T01:43:58Z"
    mac: ENC[AES256_GCM,data:/Y7WXYTE/2cUDsj5XfpAYJ58gz5fFqv+eLhhhm6BK3JkL41tG4cgIo/gl3vTqObFt7sdCrLBSCUXvVFZz7tV3SDL8aUhE/e+V1swetiduGaCpSNdjt4+5sBlm4nwrN+YTVqEyoePyRbU14gqTT4UlWOnnvVWYkjnRA8mhHmZ9Zc=,iv:ji3W9Yvr8gn6lUJkrM+9+HfsV6LBAAVDvKQ/UdizMus=,tag:8QWtik/qLi+AWrlV3wGLmw==,type:str]
    version: 3.13.2
