apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:drJWvg0kSELLDHvrVFRZQbWQf5ivC8rKhoKAm8wKF36yfqIPJA70FrFURdR2unHIJxwdtvKA4UsmhiFZg+pPbgEoHnB63RHM,iv:w/Z7JoEZ5O6iSEOf0bHr2b9oi+Z3aCMgKU3q07Ahgmk=,tag:aLp5aPWcbQS6tq00YH7gPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjclVYYXdFck8zTUFrK0dn
            NEZHQ0x1enBhM21MbGZFcUZaTWdiY0hSc0hJClNXMW9ZblZMSDdlN1BVcldtOFJJ
            WnVBOHNiakxNMkNJU0o3RE5xRnRjTGMKLS0tIFhJOUlXVXJHWVowSW9iUFEwZnJU
            eHVtQzRtOU1GTkNrUFQrRFlUdkNSTEkKbWpSymxAZAzbGSrzGX94kOe8dBv9+u2c
            sjP994yLNOn9I3DooZZ10y32bilUOKLr0F2zENyP0KAclM79X32CLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mrzxnhevexdaywfjepmxhq5vu84zshcf34z9he056zqwcxvv8vus8970cc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraHZXOW1sZlhVOWY2QjZP
            dmhoOWNtQkR6bEFSQzE0WDlDVjJrYmlQdVY4Ck5hRVZEbFNtbDBlYmkxV3NWRVJ6
            SDZnL2VGc3N5UXhMelptMXVuTlZvOGMKLS0tIFdkMzdKZDlLQ0VnRWlNQWpvcmNt
            K0F2S0RlcTVpSmQ4ZWdhVzJOL2Nwd0UKuEdWgyPDNzUaIR9VxuYsTEtXzX67Aiyi
            PuiParoQsdkBH8ydd6DBgh5TTxMZM3o5Ohq7HUc6GNtRshgu508pWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fqwlewvwa72jne30juy5u8nxkyy0x4dd06f0x0r984lmvexe954s2k5mx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T01:43:55Z"
    mac: ENC[AES256_GCM,data:/Q+mld3kaYOKSolB5ho/LkOmAA3qkxn9NB7oJZbfoFEpsWu80SQM1xEwqJaPCcAsXN6ltv/Gw96sFzc6X8Tik51VogDvqfiIS91KlUA/WBYasoDduO6MIS49KORfsr/+fRSek36kFAqfuTv4jLzK0AC+i/WCx/P0E++bF2XNvnU=,iv:IG8QdxgYd56sX0JUceEg0yj9kbXzuBdV7PnSaLm9Nl4=,tag:N7PIo8Tsiwo7DpI2iljxEA==,type:str]
    version: 3.13.2
