# ⚠️ SUBSTITUA pelo seu Cloudflare API Token com permissões:
#   - Zone:Zone:Read
#   - Zone:DNS:Edit
# Crie em: https://dash.cloudflare.com/profile/api-tokens → "Edit zone DNS" template
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:/jie71LnN2NzW/oHwdboh0MkXO+QJl1AssI+3AOspbfT5ScEwMbNMlDDNhHEHx8j0v0BhGc=,iv:3k31aOZy1MoUgAlL9HAE9o2jw1LGFM8TfbE4g0Yuz2c=,tag:2i/AOZvwvAokK9173el1hw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUnBNYmNyYmlRMjNBTlpX
            VWZ1dG5hVUx6c2FJMCt0SzNaMlM4QVA3V1cwCmE0Wng0VEh6Y1JLaFZpNHNGSmR3
            clZSRjZnVHEwVG83cHphdlJLWEtacm8KLS0tIHJwQ2ZCbEZNNUl1b0Yxc055dHpr
            Rm05ZE1aV2UvcHczeUx5OVpaSW9uVVkKpkHXB4CsPdLPe1kGYEnGnb/S+IhfyHTR
            tOUT/KcHHxvZ5KxUMibKl0DtmJteZ0hNVtoTfxgruOl4CUtYTigylA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mrzxnhevexdaywfjepmxhq5vu84zshcf34z9he056zqwcxvv8vus8970cc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaGpGaFhmd1BaMDcremxM
            YitKUll2S05lK3RqeE04ckRRbjFsL0NoZkRzCm53Z2RId0JndnVwU2lKVGdrT25r
            eHREVTliVm5Ka1o4eG9odHdGbVkwdjAKLS0tICtMVDJnYXZnSm5Wd05RbkoySXpV
            d2tLVnFycXgyVWZPc0VNYXkyOW1QNFEKjUkW6pBZ2jzZOIRATXJbsdda1PfBk+xp
            fjYzpxIEMVqavP2G5Q6NywES40RRfUCN8S8badmwUhrtxS4n6Xve6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fqwlewvwa72jne30juy5u8nxkyy0x4dd06f0x0r984lmvexe954s2k5mx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T16:28:40Z"
    mac: ENC[AES256_GCM,data:fEyC0VS+T+vfsO8dNHpaGmCBi6dS8m9G+8/fzo2Ol3v8cg8ib6RezejupL1DvaRxnojYxW7CixRZwQaatZdjahCf3TOxA2uuMGB+/1gWmt+Tu8JMt6GydRxDuz0cxBarXyqggC2fDab8H7hPlUUJ8Yw4SugWU9gi7zcH+HbVrvg=,iv:01HKQpWImiUyMdI3f0is0P3VkRuttDXLaHDREY6gcZM=,tag:xIclW+77V26sW0RlNQJZ2w==,type:str]
    version: 3.13.3
