apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: checkup
  namespace: flux-system
spec:
  image: registry.sh-lucas.dev/checkup
  interval: 5m
  secretRef:
    name: registry-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: checkup
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: checkup
  policy:
    alphabetical:
      order: asc
  filterTags:
    # Filtra tags no formato "YYYY.MM.DD--run--sha"
    pattern: '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}--[0-9]{3,4}--[a-f0-9]+$'
