apiVersion: v1
kind: Service
metadata:
  name: checkup
  namespace: checkup
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: checkup
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: checkup
  namespace: checkup
spec:
  ingressClassName: traefik
  rules:
    - host: checkup.sh-lucas.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: checkup
                port:
                  number: 80
