apiVersion: v1
kind: Secret
metadata:
    name: checkup-secrets
    namespace: checkup
type: Opaque
data:
    JWT_SECRET: ENC[AES256_GCM,data:ktSoO7vh5bi/0IV110aoxv6M8Z2nwfqMezj2qebTzaAXPIQ9gNGQIVHwcd/MganWlj6waa31bHv/5OwCTvIBwqK0nmlRIgWTXVsjt7RZIXvu2TD/n8MrkU1VGZkVrxZpIZ3bSbxuLKpaJWTqmJc0PWIaBGOOlYYx,iv:hbwMSx1LH7u2kMiAGFWTgg5RVm5rs/IHwgZf3eF4Abc=,tag:CP3tg5i7b7ZNzNuQvL8R0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBralRMZU0wVFdXamM0SW1x
            V0FBeVJQMlc1YjZjN0hIZkxtWHpkZGJmazIwCnhFT2FLLy91dEpqdlhKWDB3R2hX
            Mk40R0ZlR0lKenQ4ZVgrWVo4V1h0QVUKLS0tIDBYSFQxK2tyajRNVERqazJGWG55
            K3M4RHl0OFF6Si9HMm5TZk5BQVpBTDQKokxQgtYn4tS7ed9pYEfwE85ojOUvk1PC
            wi4ZjaJ/qhA5cnlyPsVezJeFessFxQ3tsg/ga+A4Rk9nifw+Z/DMRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mrzxnhevexdaywfjepmxhq5vu84zshcf34z9he056zqwcxvv8vus8970cc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SStYUkkyTEVRQ1p6VDNM
            ek1KUE1pTXo2ZTBKU2hJWjFyelBwMFBJdm44CkhueVBhTWhMckhhbDhsdVZaZjcw
            ZXllMy9HOEk0Mkp1Q0xWdk9NNnFIbzAKLS0tIFpkWTQyMXdKTThmaWNPSkYyblFU
            bDc4bzZiTytCVkxZanVSL1dMeHUxeWMKx6gAgDN59Rzpt3L/AlC/ruZ9aPfQes/Y
            gmisaHV5MfuU7RDGJ3Tcoka0apjTuy02I3t7RwEb293I0992aIKTsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fqwlewvwa72jne30juy5u8nxkyy0x4dd06f0x0r984lmvexe954s2k5mx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T01:43:52Z"
    mac: ENC[AES256_GCM,data:bUQijUsKd6MWZK4BsA6PK0fvbvyo1Vqr/5XBdvJ6CzRfrKsydPwcTUdPMMqK01IvY2LhUFk0N+0IR7OZHIlG/0aJERbND0DvNnOg2g/rqjAAKPydg+GheBAOTsetJXWj1e0nTHhSKv2acUTNgB4UIiuKatlMjGCNiW5AKLp1RZc=,iv:ezZB3c3mfEJDEYuzNejRh0ZhQFR+PU5k0ZX5FC/NNok=,tag:8/iwCCp440HTvupQ2aTyrw==,type:str]
    version: 3.13.2
