apiVersion: v1
kind: Secret
metadata:
    name: checkup-secrets
    namespace: checkup
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:Sdy5rjOE0OBOChNEWMPAwaNu3vpdbYd9xyf9GQZxTrBAtpDXjcn4YTrgXmLDvBtXnVEo/jdQ5ssYUihY4iTMQOqufEodvYV/xeSFLKKXwrA+us3EagDUjQ==,iv:iz8qR6UUWmcTn65ktqPDwmRgUR4Am3nT7jibh37hTtg=,tag:HlbiZVXFnxLcEDTNsj4RYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWGE4aDBXOHBPZ2pmNG1l
            eHAzQS9tZFJSUXlXaTRXcUUzY2cwYkpsNGljClZYMmdVYjliaG1xVjVDcUxZejZr
            ck52cjdEbHdZRCs5cG9ma0ZwREl4dWcKLS0tIHQrVzRwYU00WjJaQTAwa2RwTG1l
            T21XWmZMdGxiWjdIUytWM2pEYXpZZEkKefZ7zuCgL1BMSj/sQhKwSEKkdkL13YEJ
            BF5K3twoatVTxtuXE43hm+lfveUr6Bcp4V/y/gOAbqMXXu8v5gGfeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mrzxnhevexdaywfjepmxhq5vu84zshcf34z9he056zqwcxvv8vus8970cc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbmFYK0RETGhGcWpNMk8y
            S0VmT08rQnhQQ3dyZC9LNHEvZHcxSDlZaFRNCkdCWjBVR1dDN091TmZjbWlqSHMv
            dFNxNm5hMERCK3gzR0gyclVQUTFqbjgKLS0tIEVoNlkzUXhTblA0SnJ0ZElnVTVB
            MENxQlR4RGZVZlVOYzFlanRWQVEzZXcKtJCPl7FMXHebr0Dad2qbvALfYCLGQDKZ
            yfUAOnhLA0jRNrA2QoMU6WvQsremlzXCHlfVGIWEjTqR6Ll5t6QzLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fqwlewvwa72jne30juy5u8nxkyy0x4dd06f0x0r984lmvexe954s2k5mx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T16:28:40Z"
    mac: ENC[AES256_GCM,data:o+iOZZlap7YjbrgnUUNLtm/MFL/B2GC5/9BUW6CCiQX3oLSi5cmddKpQ/u0pd8kmEVDz7XRiBvMe502C1qV/IWztFrqoCO2TE4Y/c9bGlb2DGbdsMP1ixaTcSWCqsSDSKv/2PJxKqc6XZBX61J9/WvGG6/2W5yOb86S4NrfSetY=,iv:xag/TOky6wvsIq/xeP7wQp0x40z+E5pirwADWfjELYs=,tag:bzepVSRSu7nvtUtpkxQfrQ==,type:str]
    version: 3.13.3
